(define (problem Welding-domain)
   (:domain Welding-domain)
   (:objects
       base_pos_0 base_pos_1 base_pos_2 base_pos_3 base_pos_4 base_pos_5 base_pos_6 base_pos_7 base_pos_8 base_pos_9 base_pos_10 base_pos_11 base_pos_12 base_pos_13 base_pos_14 base_pos_15 base_pos_16 base_pos_17 base_pos_18 base_pos_19 base_pos_20 base_pos_21 base_pos_22 base_pos_23 base_pos_24 base_pos_25 base_pos_26 base_pos_27 base_pos_28 base_pos_29 base_pos_30 base_pos_31 base_pos_32 base_pos_33 base_pos_34 base_pos_35 base_pos_36 base_pos_37 base_pos_38 base_pos_39 base_pos_40 base_pos_41 base_pos_42 base_pos_43 base_pos_44 base_pos_45 base_pos_46 base_pos_47 base_pos_48 base_pos_49 wasted_pos_0 wasted_pos_1 wasted_pos_2 - base_location
       weld_pos_0 weld_pos_1 weld_pos_2 weld_pos_3 weld_pos_4 weld_pos_5 weld_pos_6 weld_pos_7 weld_pos_8 weld_pos_9 weld_pos_10 weld_pos_11 weld_pos_12 weld_pos_13 weld_pos_14 weld_pos_15 weld_pos_16 weld_pos_17 weld_pos_18 weld_pos_19 weld_pos_20 weld_pos_21 weld_pos_22 weld_pos_23 weld_pos_24 weld_pos_25 weld_pos_26 - weld_location
       hand_0 hand_1 hand_2 - hand
       agent_0 agent_1 agent_2 - agent
       0 1 - h_type
   )
   (:init
       (not_welded weld_pos_0)
       (weld_type weld_pos_0 1)
       (not_welded weld_pos_1)
       (weld_type weld_pos_1 1)
       (not_welded weld_pos_2)
       (weld_type weld_pos_2 1)
       (not_welded weld_pos_3)
       (weld_type weld_pos_3 1)
       (not_welded weld_pos_4)
       (weld_type weld_pos_4 1)
       (not_welded weld_pos_5)
       (weld_type weld_pos_5 1)
       (not_welded weld_pos_6)
       (weld_type weld_pos_6 1)
       (not_welded weld_pos_7)
       (weld_type weld_pos_7 1)
       (not_welded weld_pos_8)
       (weld_type weld_pos_8 1)
       (not_welded weld_pos_9)
       (weld_type weld_pos_9 1)
       (not_welded weld_pos_10)
       (weld_type weld_pos_10 1)
       (not_welded weld_pos_11)
       (weld_type weld_pos_11 0)
       (not_welded weld_pos_12)
       (weld_type weld_pos_12 1)
       (not_welded weld_pos_13)
       (weld_type weld_pos_13 0)
       (not_welded weld_pos_14)
       (weld_type weld_pos_14 1)
       (not_welded weld_pos_15)
       (weld_type weld_pos_15 0)
       (not_welded weld_pos_16)
       (weld_type weld_pos_16 1)
       (not_welded weld_pos_17)
       (weld_type weld_pos_17 1)
       (not_welded weld_pos_18)
       (weld_type weld_pos_18 0)
       (not_welded weld_pos_19)
       (weld_type weld_pos_19 1)
       (not_welded weld_pos_20)
       (weld_type weld_pos_20 1)
       (not_welded weld_pos_21)
       (weld_type weld_pos_21 0)
       (not_welded weld_pos_22)
       (weld_type weld_pos_22 0)
       (not_welded weld_pos_23)
       (weld_type weld_pos_23 0)
       (not_welded weld_pos_24)
       (weld_type weld_pos_24 0)
       (not_welded weld_pos_25)
       (weld_type weld_pos_25 0)
       (not_welded weld_pos_26)
       (weld_type weld_pos_26 0)
       (reachable base_pos_10 weld_pos_0)
       (reachable base_pos_16 weld_pos_0)
       (reachable base_pos_26 weld_pos_0)
       (reachable base_pos_12 weld_pos_0)
       (reachable base_pos_14 weld_pos_0)
       (reachable base_pos_28 weld_pos_0)
       (reachable base_pos_30 weld_pos_1)
       (reachable base_pos_32 weld_pos_1)
       (reachable base_pos_28 weld_pos_1)
       (reachable base_pos_26 weld_pos_1)
       (reachable base_pos_28 weld_pos_2)
       (reachable base_pos_38 weld_pos_2)
       (reachable base_pos_36 weld_pos_2)
       (reachable base_pos_26 weld_pos_2)
       (reachable base_pos_24 weld_pos_2)
       (reachable base_pos_22 weld_pos_3)
       (reachable base_pos_36 weld_pos_3)
       (reachable base_pos_38 weld_pos_3)
       (reachable base_pos_36 weld_pos_4)
       (reachable base_pos_40 weld_pos_4)
       (reachable base_pos_44 weld_pos_4)
       (reachable base_pos_46 weld_pos_4)
       (reachable base_pos_38 weld_pos_4)
       (reachable base_pos_42 weld_pos_4)
       (reachable base_pos_11 weld_pos_5)
       (reachable base_pos_13 weld_pos_5)
       (reachable base_pos_15 weld_pos_5)
       (reachable base_pos_17 weld_pos_5)
       (reachable base_pos_29 weld_pos_5)
       (reachable base_pos_27 weld_pos_5)
       (reachable base_pos_29 weld_pos_6)
       (reachable base_pos_27 weld_pos_6)
       (reachable base_pos_33 weld_pos_6)
       (reachable base_pos_31 weld_pos_6)
       (reachable base_pos_27 weld_pos_7)
       (reachable base_pos_29 weld_pos_7)
       (reachable base_pos_37 weld_pos_7)
       (reachable base_pos_35 weld_pos_7)
       (reachable base_pos_39 weld_pos_7)
       (reachable base_pos_25 weld_pos_7)
       (reachable base_pos_23 weld_pos_8)
       (reachable base_pos_39 weld_pos_8)
       (reachable base_pos_21 weld_pos_8)
       (reachable base_pos_37 weld_pos_8)
       (reachable base_pos_39 weld_pos_9)
       (reachable base_pos_41 weld_pos_9)
       (reachable base_pos_47 weld_pos_9)
       (reachable base_pos_43 weld_pos_9)
       (reachable base_pos_37 weld_pos_9)
       (reachable base_pos_45 weld_pos_9)
       (reachable base_pos_3 weld_pos_10)
       (reachable base_pos_1 weld_pos_10)
       (reachable base_pos_11 weld_pos_11)
       (reachable base_pos_13 weld_pos_11)
       (reachable base_pos_15 weld_pos_11)
       (reachable base_pos_1 weld_pos_12)
       (reachable base_pos_17 weld_pos_12)
       (reachable base_pos_21 weld_pos_12)
       (reachable base_pos_23 weld_pos_12)
       (reachable base_pos_27 weld_pos_12)
       (reachable base_pos_13 weld_pos_12)
       (reachable base_pos_19 weld_pos_12)
       (reachable base_pos_25 weld_pos_12)
       (reachable base_pos_15 weld_pos_12)
       (reachable base_pos_5 weld_pos_12)
       (reachable base_pos_3 weld_pos_12)
       (reachable base_pos_10 weld_pos_13)
       (reachable base_pos_12 weld_pos_13)
       (reachable base_pos_14 weld_pos_13)
       (reachable base_pos_0 weld_pos_14)
       (reachable base_pos_4 weld_pos_14)
       (reachable base_pos_16 weld_pos_14)
       (reachable base_pos_20 weld_pos_14)
       (reachable base_pos_24 weld_pos_14)
       (reachable base_pos_26 weld_pos_14)
       (reachable base_pos_2 weld_pos_14)
       (reachable base_pos_14 weld_pos_14)
       (reachable base_pos_12 weld_pos_14)
       (reachable base_pos_18 weld_pos_14)
       (reachable base_pos_22 weld_pos_14)
       (reachable base_pos_41 weld_pos_15)
       (reachable base_pos_43 weld_pos_15)
       (reachable base_pos_35 weld_pos_16)
       (reachable base_pos_39 weld_pos_16)
       (reachable base_pos_41 weld_pos_16)
       (reachable base_pos_43 weld_pos_16)
       (reachable base_pos_47 weld_pos_16)
       (reachable base_pos_49 weld_pos_16)
       (reachable base_pos_31 weld_pos_16)
       (reachable base_pos_33 weld_pos_16)
       (reachable base_pos_37 weld_pos_16)
       (reachable base_pos_45 weld_pos_16)
       (reachable base_pos_31 weld_pos_17)
       (reachable base_pos_33 weld_pos_17)
       (reachable base_pos_35 weld_pos_17)
       (reachable base_pos_43 weld_pos_17)
       (reachable base_pos_45 weld_pos_17)
       (reachable base_pos_47 weld_pos_17)
       (reachable base_pos_49 weld_pos_17)
       (reachable base_pos_37 weld_pos_17)
       (reachable base_pos_39 weld_pos_17)
       (reachable base_pos_40 weld_pos_18)
       (reachable base_pos_42 weld_pos_18)
       (reachable base_pos_30 weld_pos_19)
       (reachable base_pos_32 weld_pos_19)
       (reachable base_pos_34 weld_pos_19)
       (reachable base_pos_36 weld_pos_19)
       (reachable base_pos_38 weld_pos_19)
       (reachable base_pos_40 weld_pos_19)
       (reachable base_pos_42 weld_pos_19)
       (reachable base_pos_44 weld_pos_19)
       (reachable base_pos_46 weld_pos_19)
       (reachable base_pos_48 weld_pos_19)
       (reachable base_pos_30 weld_pos_20)
       (reachable base_pos_34 weld_pos_20)
       (reachable base_pos_36 weld_pos_20)
       (reachable base_pos_38 weld_pos_20)
       (reachable base_pos_42 weld_pos_20)
       (reachable base_pos_44 weld_pos_20)
       (reachable base_pos_46 weld_pos_20)
       (reachable base_pos_48 weld_pos_20)
       (reachable base_pos_32 weld_pos_20)
       (reachable base_pos_11 weld_pos_21)
       (reachable base_pos_13 weld_pos_21)
       (reachable base_pos_15 weld_pos_21)
       (reachable base_pos_21 weld_pos_21)
       (reachable base_pos_23 weld_pos_21)
       (reachable base_pos_25 weld_pos_21)
       (reachable base_pos_27 weld_pos_21)
       (reachable base_pos_29 weld_pos_21)
       (reachable base_pos_23 weld_pos_22)
       (reachable base_pos_25 weld_pos_22)
       (reachable base_pos_27 weld_pos_22)
       (reachable base_pos_10 weld_pos_23)
       (reachable base_pos_12 weld_pos_23)
       (reachable base_pos_14 weld_pos_23)
       (reachable base_pos_20 weld_pos_23)
       (reachable base_pos_22 weld_pos_23)
       (reachable base_pos_24 weld_pos_23)
       (reachable base_pos_26 weld_pos_23)
       (reachable base_pos_28 weld_pos_23)
       (reachable base_pos_22 weld_pos_24)
       (reachable base_pos_24 weld_pos_24)
       (reachable base_pos_26 weld_pos_24)
       (reachable base_pos_31 weld_pos_25)
       (reachable base_pos_35 weld_pos_25)
       (reachable base_pos_33 weld_pos_25)
       (reachable base_pos_30 weld_pos_26)
       (reachable base_pos_34 weld_pos_26)
       (reachable base_pos_32 weld_pos_26)
       (at hand_0 weld_pos_4)
       (hand_type hand_0 0)
       (at hand_1 weld_pos_17)
       (hand_type hand_1 1)
       (at hand_2 weld_pos_5)
       (hand_type hand_2 1)
       (at agent_0 base_pos_44)
       (at agent_1 base_pos_37)
       (at agent_2 base_pos_17)
       (hand_rel agent_0 hand_0)
       (hand_rel agent_1 hand_1)
       (hand_rel agent_2 hand_2)
       (empty base_pos_0)
       (empty base_pos_1)
       (empty base_pos_2)
       (empty base_pos_3)
       (empty base_pos_4)
       (empty base_pos_5)
       (empty base_pos_6)
       (empty base_pos_7)
       (empty base_pos_8)
       (empty base_pos_9)
       (empty base_pos_10)
       (empty base_pos_11)
       (empty base_pos_12)
       (empty base_pos_13)
       (empty base_pos_14)
       (empty base_pos_15)
       (empty base_pos_16)
       (empty base_pos_18)
       (empty base_pos_19)
       (empty base_pos_20)
       (empty base_pos_21)
       (empty base_pos_22)
       (empty base_pos_23)
       (empty base_pos_24)
       (empty base_pos_25)
       (empty base_pos_26)
       (empty base_pos_27)
       (empty base_pos_28)
       (empty base_pos_29)
       (empty base_pos_30)
       (empty base_pos_31)
       (empty base_pos_32)
       (empty base_pos_33)
       (empty base_pos_34)
       (empty base_pos_35)
       (empty base_pos_36)
       (empty base_pos_38)
       (empty base_pos_39)
       (empty base_pos_40)
       (empty base_pos_41)
       (empty base_pos_42)
       (empty base_pos_43)
       (empty base_pos_45)
       (empty base_pos_46)
       (empty base_pos_47)
       (empty base_pos_48)
       (empty base_pos_49)
       (empty wasted_pos_0)
       (empty wasted_pos_1)
       (empty wasted_pos_2)
       (empty weld_pos_0)
       (empty weld_pos_1)
       (empty weld_pos_2)
       (empty weld_pos_3)
       (empty weld_pos_4)
       (empty weld_pos_5)
       (empty weld_pos_6)
       (empty weld_pos_7)
       (empty weld_pos_8)
       (empty weld_pos_9)
       (empty weld_pos_10)
       (empty weld_pos_11)
       (empty weld_pos_12)
       (empty weld_pos_13)
       (empty weld_pos_14)
       (empty weld_pos_15)
       (empty weld_pos_16)
       (empty weld_pos_17)
       (empty weld_pos_18)
       (empty weld_pos_19)
       (empty weld_pos_20)
       (empty weld_pos_21)
       (empty weld_pos_22)
       (empty weld_pos_23)
       (empty weld_pos_24)
       (empty weld_pos_25)
       (empty weld_pos_26)
   )
   (:goal (and (welded weld_pos_0) (welded weld_pos_1) (welded weld_pos_2) (welded weld_pos_3) (welded weld_pos_4) (welded weld_pos_5) (welded weld_pos_6) (welded weld_pos_7) (welded weld_pos_8) (welded weld_pos_9) (welded weld_pos_10) (welded weld_pos_11) (welded weld_pos_12) (welded weld_pos_13) (welded weld_pos_14) (welded weld_pos_15) (welded weld_pos_16) (welded weld_pos_17) (welded weld_pos_18) (welded weld_pos_19) (welded weld_pos_20) (welded weld_pos_21) (welded weld_pos_22) (welded weld_pos_23) (welded weld_pos_24) (welded weld_pos_25) (welded weld_pos_26)))
)
